require File.dirname(__FILE__) + '/hornetq/lib/hornetq-core-client.jar'
require File.dirname(__FILE__) + '/hornetq/lib/netty.jar'
require 'hornetq/org_hornetq_api_core_client_client_session'
require 'hornetq/org_hornetq_core_client_impl_client_message_impl'
require 'hornetq/org_hornetq_utils_typed_properties'
require 'hornetq/hornet_q_client'
require 'hornetq/client_requestor'
require 'hornetq/client_server'
require 'hornetq/session_pool'
